// Generated by scripts/build-assets.mjs — do not edit by hand.
// Run `npm run assets` after changing the source folder.

export type Media = {
  src: string;
  width: number;
  height: number;
  alt: string;
};

export type ProjectMedia = {
  hero: Media;
  gallery: Media[];
  sheets: Media[];
};

export const media: Record<string, ProjectMedia> = {
  "the-haven": {
    "hero": {
      "src": "/media/the-haven/hero.jpg",
      "width": 1920,
      "height": 1482,
      "alt": "Courtyard between the housing blocks at dusk, children playing on the path"
    },
    "gallery": [
      {
        "src": "/media/the-haven/01.jpg",
        "width": 901,
        "height": 862,
        "alt": "The housing cluster at night, festoon lights strung between the steel frames"
      },
      {
        "src": "/media/the-haven/02.jpg",
        "width": 2000,
        "height": 1647,
        "alt": "Site analysis of Al Laylake: zoning, circulation and the Ghadir river corridor"
      },
      {
        "src": "/media/the-haven/03.jpg",
        "width": 1920,
        "height": 1854,
        "alt": "Elevated walkway under the prefabricated units"
      },
      {
        "src": "/media/the-haven/04.jpg",
        "width": 2000,
        "height": 1990,
        "alt": "Master plan of the compound with its shared agricultural courtyards"
      },
      {
        "src": "/media/the-haven/05.jpg",
        "width": 1920,
        "height": 1854,
        "alt": "Shared ground level beneath the raised housing blocks"
      },
      {
        "src": "/media/the-haven/06.jpg",
        "width": 2000,
        "height": 977,
        "alt": "Cluster 3D assembly: raising structure, hallway, core, unit, partition and shading"
      },
      {
        "src": "/media/the-haven/07.jpg",
        "width": 1920,
        "height": 1854,
        "alt": "Balconies with their sliding scrap-wood louvres"
      },
      {
        "src": "/media/the-haven/08.jpg",
        "width": 533,
        "height": 2000,
        "alt": "Unit plans for the 60 m² and 80 m² variants"
      },
      {
        "src": "/media/the-haven/09.jpg",
        "width": 1920,
        "height": 1854,
        "alt": "Planting beds and circulation through the compound"
      },
      {
        "src": "/media/the-haven/10.jpg",
        "width": 1899,
        "height": 1381,
        "alt": "Exploded wall and floor build-up, from eco concrete to the hollow steel frame"
      },
      {
        "src": "/media/the-haven/11.jpg",
        "width": 2000,
        "height": 621,
        "alt": "Long section through the block showing the elevated steel platform"
      },
      {
        "src": "/media/the-haven/12.jpg",
        "width": 2000,
        "height": 541,
        "alt": "Elevation study, louvre colours distinguishing the unit types"
      },
      {
        "src": "/media/the-haven/13.jpg",
        "width": 2000,
        "height": 510,
        "alt": "Second elevation study across the cluster"
      },
      {
        "src": "/media/the-haven/14.jpg",
        "width": 2000,
        "height": 658,
        "alt": "Module studies: the 9.6 m and 7.8 m prefabricated boxes"
      },
      {
        "src": "/media/the-haven/15.jpg",
        "width": 340,
        "height": 748,
        "alt": "Shading study for the sliding louvre panels"
      },
      {
        "src": "/media/the-haven/16.jpg",
        "width": 320,
        "height": 708,
        "alt": "Second shading study across the balcony edge"
      },
      {
        "src": "/media/the-haven/17.jpg",
        "width": 2000,
        "height": 1149,
        "alt": "Diagram of agricultural significance and the agro-healing cycle"
      },
      {
        "src": "/media/the-haven/18.jpg",
        "width": 2000,
        "height": 1614,
        "alt": "Off-site construction sequence, modules craned into the steel frame"
      }
    ],
    "sheets": [
      {
        "src": "/media/the-haven/sheets/01.jpg",
        "width": 1400,
        "height": 990,
        "alt": "Portfolio sheet 01 — context and site analysis"
      },
      {
        "src": "/media/the-haven/sheets/02.jpg",
        "width": 1400,
        "height": 990,
        "alt": "Portfolio sheet 02 — concept and modular strategy"
      },
      {
        "src": "/media/the-haven/sheets/03.jpg",
        "width": 1400,
        "height": 990,
        "alt": "Portfolio sheet 03 — plans, sections and elevations"
      },
      {
        "src": "/media/the-haven/sheets/04.jpg",
        "width": 1400,
        "height": 990,
        "alt": "Portfolio sheet 04 — structure and low carbon design"
      }
    ]
  },
  "narrative-of-jbeil": {
    "hero": {
      "src": "/media/narrative-of-jbeil/hero.jpg",
      "width": 1920,
      "height": 1080,
      "alt": "The design district's perforated copper screen above the garden at Byblos"
    },
    "gallery": [
      {
        "src": "/media/narrative-of-jbeil/01.jpg",
        "width": 1920,
        "height": 1080,
        "alt": "The building at night, the screen lit from within"
      },
      {
        "src": "/media/narrative-of-jbeil/02.jpg",
        "width": 1920,
        "height": 1616,
        "alt": "Day and night comparison of the same elevation"
      },
      {
        "src": "/media/narrative-of-jbeil/03.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Elevations reading the Bronze Age, Roman and Ottoman periods of Jbeil"
      },
      {
        "src": "/media/narrative-of-jbeil/04.jpg",
        "width": 1920,
        "height": 1080,
        "alt": "Meeting room behind the mashrabiya-like shaders"
      },
      {
        "src": "/media/narrative-of-jbeil/05.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Concept study for the design district"
      },
      {
        "src": "/media/narrative-of-jbeil/06.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Site strategy among the historical landmarks of Byblos"
      },
      {
        "src": "/media/narrative-of-jbeil/07.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Plan of the three studios and their creative loop"
      },
      {
        "src": "/media/narrative-of-jbeil/08.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Section through the design district"
      },
      {
        "src": "/media/narrative-of-jbeil/09.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Studio A — open collaboration space"
      },
      {
        "src": "/media/narrative-of-jbeil/10.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Studio B — fabrication labs and materials testing"
      },
      {
        "src": "/media/narrative-of-jbeil/11.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Studio C — the virtual reality lab"
      },
      {
        "src": "/media/narrative-of-jbeil/12.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Facade detail of the copper screen"
      },
      {
        "src": "/media/narrative-of-jbeil/13.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Circulation and wayfinding through the district"
      },
      {
        "src": "/media/narrative-of-jbeil/14.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Material study of steel and Byblos stone"
      }
    ],
    "sheets": []
  },
  "journey-to-utopia": {
    "hero": {
      "src": "/media/journey-to-utopia/hero.jpg",
      "width": 1920,
      "height": 902,
      "alt": "The funicular arch trail in low sun, light patterning the timber deck"
    },
    "gallery": [
      {
        "src": "/media/journey-to-utopia/01.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Concept for the temporary art trail on Gouraud Street"
      },
      {
        "src": "/media/journey-to-utopia/02.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "The three sites: the street trail, the main and secondary structures"
      },
      {
        "src": "/media/journey-to-utopia/03.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Funicular arch geometry meeting the inclined ring beam"
      },
      {
        "src": "/media/journey-to-utopia/04.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Structural study of the radial arches"
      },
      {
        "src": "/media/journey-to-utopia/05.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Plan of the trail through Gemmayzeh"
      },
      {
        "src": "/media/journey-to-utopia/06.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Section through the main structure"
      },
      {
        "src": "/media/journey-to-utopia/07.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "The secondary structure on the adjacent site"
      },
      {
        "src": "/media/journey-to-utopia/08.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Steel beams spanning across the funicular arches"
      },
      {
        "src": "/media/journey-to-utopia/09.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Light and shadow study through the arch lattice"
      },
      {
        "src": "/media/journey-to-utopia/10.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "The trail seen from the street"
      }
    ],
    "sheets": []
  },
  "ephemeral-luminance": {
    "hero": {
      "src": "/media/ephemeral-luminance/hero.jpg",
      "width": 2000,
      "height": 992,
      "alt": "The 3 × 3 × 3 m grid structure glowing in the dark, figures beneath it"
    },
    "gallery": [
      {
        "src": "/media/ephemeral-luminance/01.jpg",
        "width": 1269,
        "height": 809,
        "alt": "Illustration of the illuminated grid and its interchangeable partitions"
      },
      {
        "src": "/media/ephemeral-luminance/02.jpg",
        "width": 2000,
        "height": 1013,
        "alt": "Narrative one — the maze, light contouring the visitor's path"
      },
      {
        "src": "/media/ephemeral-luminance/03.jpg",
        "width": 2000,
        "height": 779,
        "alt": "The maze — sequence of views towards the garden of light"
      },
      {
        "src": "/media/ephemeral-luminance/04.jpg",
        "width": 1294,
        "height": 1290,
        "alt": "The maze — plan of the maze-like partition layout"
      },
      {
        "src": "/media/ephemeral-luminance/05.jpg",
        "width": 2000,
        "height": 453,
        "alt": "The maze — sections through the grid"
      },
      {
        "src": "/media/ephemeral-luminance/06.jpg",
        "width": 881,
        "height": 1076,
        "alt": "The maze — partition types, including Kahn's circular openings"
      },
      {
        "src": "/media/ephemeral-luminance/07.jpg",
        "width": 2000,
        "height": 1014,
        "alt": "Narrative two — the legend of Inanna, daylight dimming through the descent"
      },
      {
        "src": "/media/ephemeral-luminance/08.jpg",
        "width": 2000,
        "height": 797,
        "alt": "Inanna — sequence of views through the descent and return"
      },
      {
        "src": "/media/ephemeral-luminance/09.jpg",
        "width": 1339,
        "height": 1381,
        "alt": "Inanna — plans of the deconstructed cube arrangement"
      },
      {
        "src": "/media/ephemeral-luminance/10.jpg",
        "width": 2000,
        "height": 444,
        "alt": "Inanna — section through the narrative"
      },
      {
        "src": "/media/ephemeral-luminance/11.jpg",
        "width": 914,
        "height": 1162,
        "alt": "Inanna — partitions after Richard Meier's deconstructed cubes"
      },
      {
        "src": "/media/ephemeral-luminance/12.jpg",
        "width": 2000,
        "height": 1021,
        "alt": "Narrative three — stability and instability, the breakpoint"
      },
      {
        "src": "/media/ephemeral-luminance/13.jpg",
        "width": 2000,
        "height": 794,
        "alt": "Stability and instability — sequence towards the spiritual oasis"
      },
      {
        "src": "/media/ephemeral-luminance/14.jpg",
        "width": 1328,
        "height": 1400,
        "alt": "Stability and instability — plan of the fragmented labyrinth"
      },
      {
        "src": "/media/ephemeral-luminance/15.jpg",
        "width": 2000,
        "height": 453,
        "alt": "Stability and instability — section through the labyrinth"
      },
      {
        "src": "/media/ephemeral-luminance/16.jpg",
        "width": 968,
        "height": 1335,
        "alt": "Stability and instability — thick hollow partitions after Ronchamp"
      },
      {
        "src": "/media/ephemeral-luminance/17.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Competition board — concept and parameters"
      },
      {
        "src": "/media/ephemeral-luminance/18.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Competition board — grid structure"
      },
      {
        "src": "/media/ephemeral-luminance/19.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Competition board — materials and light"
      },
      {
        "src": "/media/ephemeral-luminance/20.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Competition board — the maze"
      },
      {
        "src": "/media/ephemeral-luminance/21.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Competition board — the legend of Inanna"
      },
      {
        "src": "/media/ephemeral-luminance/22.jpg",
        "width": 2000,
        "height": 1415,
        "alt": "Competition board — stability and instability"
      }
    ],
    "sheets": [
      {
        "src": "/media/ephemeral-luminance/sheets/01.jpg",
        "width": 1400,
        "height": 788,
        "alt": "VELUX competition board, full spread"
      }
    ]
  }
};

export const singles: Record<string, Media> = {
  "portrait": {
    "src": "/media/portrait.jpg",
    "width": 1047,
    "height": 896,
    "alt": "Nadia Abdel Sater"
  },
  "pattern-light": {
    "src": "/media/pattern-light.jpg",
    "width": 1374,
    "height": 580,
    "alt": ""
  },
  "pattern-dark": {
    "src": "/media/pattern-dark.jpg",
    "width": 1374,
    "height": 580,
    "alt": ""
  }
};

export const heroVideo = {
  "mp4": "/media/hero/hero.mp4",
  "mobile": "/media/hero/hero-mobile.mp4",
  "poster": "/media/hero/poster.jpg"
};
